name: 功能需求
description: 为项目提供建议
title: "以简单的一段字概括你的建议"
body:
  - type: markdown
    attributes:
      value: |
        ## 反馈须知
        - 请务必完整填写下面的内容，如果缺少必要的信息，可能会在未核实的情况下直接关闭
        - 一个 issue 请只反馈一个 bug 或功能建议，一次性反馈多个不同的问题或建议将会直接关闭（因为这不便于追踪问题）
        - 注意你的标题，以简单的一段字概括你所遇到的问题。无意义标题直接关闭

  - type: textarea
    id: problem-description
    validations:
      required: true
    attributes:
      label: 问题描述
      description: 描述你想要解决的问题或者功能的使用场景
      placeholder: 请描述你遇到的问题或者链接到已存在的 issue
  - type: textarea
    id: solution-description
    validations:
      required: true
    attributes:
      label: 描述解决方案
      description: 清晰简明地描述你所想要发生的事情，即解决方案
  - type: textarea
    id: alternatives
    attributes:
      label: 描述备选方案
      description: 解决该问题的备选方案
  - type: textarea
    id: additional-info
    attributes:
      label: 附加信息
      description: 添加你认为有必要的信息
